"""
Django settings for LeafyReads project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from environ import Env
env = Env()
Env.read_env()

ENVIRONMENT = env('ENVIRONMENT', default='production')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret
SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'home.apps.HomeConfig',
    'books.apps.BooksConfig',
    'LRAdmin.apps.LradminConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LeafyReads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LeafyReads.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_ROOT = BASE_DIR /"media"
MEDIA_URL = '/media/'
CKEDITOR5_UPLOAD_PATH = "uploads/"


customColorPalette = [
    {'color': 'hsl(0, 0%, 0%)', 'label': 'Black'},
    {'color': 'hsl(0, 0%, 30%)', 'label': 'Dim grey'},
    {'color': 'hsl(0, 0%, 60%)', 'label': 'Grey'},
    {'color': 'hsl(0, 0%, 90%)', 'label': 'Light grey'},
    {'color': 'hsl(0, 0%, 100%)', 'label': 'White'},
    {'color': 'hsl(0, 75%, 60%)', 'label': 'Red'},
    {'color': 'hsl(0, 75%, 30%)', 'label': 'Dark red'},
    {'color': 'hsl(30, 75%, 60%)', 'label': 'Orange'},
    {'color': 'hsl(30, 75%, 30%)', 'label': 'Dark orange'},
    {'color': 'hsl(60, 75%, 60%)', 'label': 'Yellow'},
    {'color': 'hsl(60, 75%, 30%)', 'label': 'Dark yellow'},
    {'color': 'hsl(100, 75%, 60%)', 'label': 'Light green'},
    {'color': 'hsl(100, 75%, 30%)', 'label': 'Dark green'},
    {'color': 'hsl(135, 75%, 60%)', 'label': 'Green'},
    {'color': 'hsl(135, 75%, 30%)', 'label': 'Dark green'},
    {'color': 'hsl(165, 75%, 60%)', 'label': 'Cyan'},
    {'color': 'hsl(165, 75%, 30%)', 'label': 'Dark cyan'},
    {'color': 'hsl(195, 75%, 60%)', 'label': 'Light blue'},
    {'color': 'hsl(195, 75%, 30%)', 'label': 'Dark blue'},
    {'color': 'hsl(225, 75%, 60%)', 'label': 'Blue'},
    {'color': 'hsl(225, 75%, 30%)', 'label': 'Dark blue'},
    {'color': 'hsl(270, 75%, 60%)', 'label': 'Purple'},
    {'color': 'hsl(270, 75%, 30%)', 'label': 'Dark purple'},
    {'color': 'hsl(300, 75%, 60%)', 'label': 'Light purple'},
    {'color': 'hsl(300, 75%, 30%)', 'label': 'Dark purple'}
]

# CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage" # optional
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
                    }

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': {
            'items': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                      'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',
                    ],
            'shouldNotGroupWhenFull': 'true'
        },
        'mediaEmbed': {
            'previewsInData': True,
            'extraProviders': [
                {
                    'name': 'youtube',
                    'url': r'^https?://(www\.)?youtube\.com/watch\?v=.+',
                    'html': '<div class="video-container"><iframe src="{url}" frameborder="0" allowfullscreen></iframe></div>'
                },
                {
                    'name': 'vimeo',
                    'url': r'^https?://(www\.)?vimeo\.com/.+',
                    'html': '<div class="video-container"><iframe src="{url}" frameborder="0" allowfullscreen></iframe></div>'
                }
            ]
        },

        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

CKEDITOR_5_FILE_UPLOAD_PERMISSION = None  # allow all users to upload temporarily
CKEDITOR_5_IMAGE_BACKEND = "pillow"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
