# Generated by Django 5.2.2 on 2025-10-31 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LRAdmin', '0001_initial'),
        ('books', '0002_alter_book_audio_file_alter_book_cover_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklog',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='books.book'),
        ),
    ]
