# Generated by Django 5.2.2 on 2025-10-25 13:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_front',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
