# Generated by Django 5.2.2 on 2025-12-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_audio_file_alter_book_cover_front_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='like',
            name='books_like_book_id_a518f7_idx',
        ),
    ]
