# Generated by Django 5.2.2 on 2025-12-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_like_books_like_book_id_a518f7_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_genre_i_ccb207_idx',
        ),
        migrations.RemoveIndex(
            model_name='readby',
            name='books_readb_book_id_4276e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='readlater',
            name='books_readl_book_id_3c558a_idx',
        ),
    ]
