# Generated by Django 5.2.2 on 2025-08-28 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_genre_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'book'], name='books_like_user_id_66fdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='readlater',
            index=models.Index(fields=['user', 'book'], name='books_readl_user_id_85eebd_idx'),
        ),
    ]
