# Generated by Django 5.2.2 on 2025-12-02 13:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_enable_trigram'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'author'], name='book_title_author_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
