# Generated by Django 5.2.2 on 2025-12-02 13:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_book_title_author_trgm_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_title_author_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'author', 'slug'], name='book_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
