# Generated by Django 5.2.2 on 2025-12-04 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_book_book_title_author_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio_file'),
        ),
    ]
