# Generated by Django 5.2.2 on 2025-09-28 11:25

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre'], name='books_book_genre_i_ccb207_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-uploaded_at'], name='books_book_uploade_a7ba42_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'author'], name='books_book_title_b58b85_gin'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='books_categ_name_edff05_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['category', 'slug'], name='books_genre_categor_b5b3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['book'], name='books_like_book_id_a518f7_idx'),
        ),
        migrations.AddIndex(
            model_name='readlater',
            index=models.Index(fields=['book'], name='books_readl_book_id_3c558a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book', 'user'], name='books_revie_book_id_c4fa17_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='books_revie_created_5162e5_idx'),
        ),
    ]
