# Generated by Django 5.2.2 on 2025-12-04 15:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
    ]
