# Generated by Django 5.2.2 on 2025-12-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
