# Generated by Django 5.2.2 on 2025-12-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_bookcontent_chunks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_searched', models.DateTimeField(auto_now_add=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Failed Search Term',
                'verbose_name_plural': 'Failed Search Terms',
                'ordering': ['-last_searched'],
            },
        ),
    ]
