# Generated by Django 5.2.2 on 2026-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_searchquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
