# Generated by Django 5.2.2 on 2026-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
