# Generated by Django 5.2.2 on 2026-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_likes_count_book_read_later_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
