# Generated by Django 5.2.2 on 2026-07-26 19:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
