# Generated by Django 5.2.2 on 2025-12-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='community_c_post_id_626a6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='community_c_author__1e6995_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='community_c_parent__5a3862_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='community_n_recipie_1210a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='community_p_author__5261da_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='community_p_book_id_159870_idx',
        ),
    ]
