# Generated by Django 5.2.2 on 2026-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('book_mention', 'Book Mention'), ('post_publish', 'Post Published'), ('like', 'Like'), ('draft_saved', 'Draft Saved'), ('book_review', 'Book Under Review'), ('book_published', 'Book Published')], max_length=20),
        ),
    ]
