# Generated by Django 5.2.2 on 2026-02-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='promotional_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('promotion', 'promotion'), ('comment', 'Comment'), ('book_mention', 'Book Mention'), ('post_publish', 'Post Published'), ('like', 'Like'), ('draft_saved', 'Draft Saved'), ('book_review', 'Book Under Review'), ('book_published', 'Book Published')], max_length=20),
        ),
    ]
