# Generated by Django 5.2.2 on 2026-02-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='type',
            new_name='feedback_type',
        ),
    ]
